apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: freelancercrm
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      imagePullSecrets:               # <- secret med PAT for GHCR
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/enock97/freelancercrm-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: apiUrl
            - name: HOST
              value: "0.0.0.0"
