name: Build-and-Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND_LATEST: ghcr.io/enock97/freelancercrm-backend:latest
  IMAGE_FRONTEND_LATEST: ghcr.io/enock97/freelancercrm-frontend:latest
  KUBE_NAMESPACE: freelancercrm

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Generate short SHA tag
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND_LATEST }}
            ghcr.io/enock97/freelancercrm-backend:${{ steps.vars.outputs.sha }}

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND_LATEST }}
            ghcr.io/enock97/freelancercrm-frontend:${{ steps.vars.outputs.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Create KinD cluster
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: v0.24.0

      - name: Install local-path storage (for PVCs)
        run: |
          kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
          kubectl patch storageclass local-path \
            -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

      - name: Pull & load images into KinD
        run: |
          docker pull ${{ env.IMAGE_BACKEND_LATEST }}
          docker pull ${{ env.IMAGE_FRONTEND_LATEST }}
          kind load docker-image ${{ env.IMAGE_BACKEND_LATEST }}
          kind load docker-image ${{ env.IMAGE_FRONTEND_LATEST }}

      - name: Create Kubernetes Secrets
        env:
          POSTGRES_USER:     ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB:       ${{ secrets.POSTGRES_DB }}
          KUBE_NAMESPACE:    ${{ env.KUBE_NAMESPACE }}
        run: |
          kubectl create namespace "$KUBE_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic pg-secret \
            --from-literal=POSTGRES_USER="$POSTGRES_USER" \
            --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            --from-literal=POSTGRES_DB="$POSTGRES_DB" \
            --namespace="$KUBE_NAMESPACE"
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username="${{ github.actor }}" \
            --docker-password="${{ secrets.REGISTRY_TOKEN }}" \
            --namespace="$KUBE_NAMESPACE"

      - name: Deploy & debug
        run: |
          # 1) Apply all your manifests
          kubectl apply -f k8s/

          # 2) Show overall Pod & Event state
          echo "=== PODS ==="
          kubectl get pods -n ${{ env.KUBE_NAMESPACE }}

          echo "=== RECENT EVENTS ==="
          kubectl get events -n ${{ env.KUBE_NAMESPACE }} --sort-by='.lastTimestamp'

          # 3) Inspect Postgres
          echo "=== DESCRIBE POSTGRES STATEFULSET ==="
          kubectl describe statefulset postgres -n ${{ env.KUBE_NAMESPACE }}

          echo "=== POSTGRES POD ==="
          kubectl get pod -l app=postgres -n ${{ env.KUBE_NAMESPACE }}

          echo "=== POSTGRES LOGS ==="
          kubectl logs -l app=postgres -n ${{ env.KUBE_NAMESPACE }} || true

          # 4) Inspect Backend
          echo "=== DESCRIBE BACKEND POD ==="
          kubectl describe pod -l app=backend -n ${{ env.KUBE_NAMESPACE }}

          echo "=== BACKEND EVENTS ==="
          kubectl get events \
            -n ${{ env.KUBE_NAMESPACE }} \
            --field-selector involvedObject.kind=Pod,involvedObject.name=$(kubectl get pod -l app=backend -n ${{ env.KUBE_NAMESPACE }} -o jsonpath='{.items[0].metadata.name}') \
            --sort-by='.lastTimestamp'

          echo "=== BACKEND LOGS ==="
          kubectl logs -l app=backend -n ${{ env.KUBE_NAMESPACE }} --all-containers || true

          # 5) Inspect Frontend
          echo "=== DESCRIBE FRONTEND POD ==="
          kubectl describe pod -l app=frontend -n ${{ env.KUBE_NAMESPACE }}

          echo "=== FRONTEND LOGS ==="
          kubectl logs -l app=frontend -n ${{ env.KUBE_NAMESPACE }} --all-containers || true

      - name: Wait for Postgres Pod to be Ready
        run: |
          kubectl wait --for=condition=Ready pod \
            -l app=postgres \
            -n ${{ env.KUBE_NAMESPACE }} \
            --timeout=180s

      - name: Wait for Backend rollout
        run: |
          kubectl rollout status deployment/backend \
            -n ${{ env.KUBE_NAMESPACE }} --timeout=120s

      - name: Wait for Frontend rollout
        run: |
          kubectl rollout status deployment/frontend \
            -n ${{ env.KUBE_NAMESPACE }} --timeout=120s
