# .github/workflows/deploy.yml
deploy:
  needs: build-push
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    # install kubectl
    - uses: azure/setup-kubectl@v3
      with: { version: 'latest' }

    # create a KinD cluster
    - name: Create KinD cluster
      uses: engineerd/setup-kind@v0.6.0
      with: { version: v0.17.0 }

    # load your images into that cluster
    - name: Load images into KinD
      run: |
        kind load docker-image ${{ env.IMAGE_BACKEND_LATEST }}
        kind load docker-image ${{ env.IMAGE_FRONTEND_LATEST }}

    # now apply your manifests
    - name: Deploy to KinD
      run: |
        kubectl apply -f k8s/
        kubectl rollout status deploy/backend  -n ${{ env.KUBE_NAMESPACE }} --timeout=120s
        kubectl rollout status deploy/frontend -n ${{ env.KUBE_NAMESPACE }} --timeout=120s
