name: Build-and-Deploy

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ${{ env.REGISTRY }}/enock97/freelancercrm-backend
  IMAGE_FRONTEND: ${{ env.REGISTRY }}/enock97/freelancercrm-frontend
  KUBE_NAMESPACE: freelancercrm

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_PAT }}

      - name: Build + push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      - name: Build + push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:latest

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Decode kube-config
        run: echo "${{ secrets.KUBE_CONFIG_B64 }}" | base64 -d > $HOME/.kube/config
      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/ # alt i mappa
          kubectl rollout status deploy/backend   -n ${{ env.KUBE_NAMESPACE }}
          kubectl rollout status deploy/frontend -n ${{ env.KUBE_NAMESPACE }}
