# .github/workflows/heroku-deploy.yml
name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # (optional) Add build/test steps here

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v4.2.0
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "freelancercrm-backend"
          heroku_email: "enockladu@hotmail.com"
