name: Deploy to Heroku

on:
  push:
    branches:
      - main   # Change to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18   # Or whatever Node version you need

      # Optionally install dependencies and build, if your Heroku buildpacks don't handle it
      - name: Install dependencies
        run: npm ci
        
      # (Optional) If you use Prisma generate during build, run it here too
      - name: Generate Prisma client
        run: npx prisma generate

      # Deploy to Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "freelancercrm-backend"
          heroku_email: "enockladu@hotmail.com"
          dontuseforce: true
