# .github/workflows/tests.yml
name: Tests only
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root deps
        run: npm ci

      - name: Install frontend deps & run tests
        run: |
          cd frontend
          npm ci
          npm test -- --ci --passWithNoTests

      - name: Install backend deps & run tests
        run: |
          cd backend
          npm ci
          npm test -- --ci --passWithNoTests
